version: '3'
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev #if file is diff than convention
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #"bookmark" and hold this folder in the container so following maps do not affect it 
      - .:/app #This is the same as map the "pwd" folder to the containers "/app" folder
  tests: #building a second container to run just the tests anytime the content changes
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] #override default command to be this
    